import { create } from 'zustand'
import type { SiteContext, SiteLoadingStates, InsightBullet } from '@/types/siteContext'
import { emptyConstraints } from '@/types/constraints'

interface SiteStore {
  /** The assembled spatial evidence container. Null when no site is selected. */
  siteContext: SiteContext | null

  /** Per-source loading state for progressive UI updates */
  loadingStates: SiteLoadingStates

  error: string | null

  /** AI insight text generated by Gemini, cached globally so map layers can read it */
  insight: string | null
  insightLoading: boolean
  insightError: string | null

  /** Structured AI insight bullets, one per category, for inline section display */
  insightBullets: InsightBullet[] | null

  /**
   * planning_reference of the precedent card currently hovered in the side panel.
   * MapCanvas reads this to render a highlight + Popup on the map.
   */
  hoveredPrecedentId: string | null

  /**
   * Initialise a new SiteContext with siteId + siteGeometry.
   * Called at the start of site selection to open the panel immediately.
   */
  initialiseSiteContext: (siteId: string, siteGeometry: GeoJSON.Geometry) => void

  /**
   * Merge partial SiteContext fields as each data source resolves.
   * No computed values should ever be passed here — raw spatial evidence only.
   */
  updateSiteContext: (partial: Partial<SiteContext>) => void

  /** Clear everything — called when user closes the panel */
  clearSiteContext: () => void

  setLoading: (source: keyof SiteLoadingStates, loading: boolean) => void
  setError: (error: string | null) => void

  setInsight: (insight: string) => void
  setInsightLoading: (loading: boolean) => void
  setInsightError: (error: string | null) => void
  setInsightBullets: (bullets: InsightBullet[]) => void
  clearInsight: () => void

  setHoveredPrecedentId: (id: string | null) => void
}

const DEFAULT_LOADING: SiteLoadingStates = {
  precedent: false,
  stats: false,
  constraints: false,
  contextFeatures: false,
}

export const useSiteStore = create<SiteStore>((set) => ({
  siteContext: null,
  loadingStates: DEFAULT_LOADING,
  error: null,
  insight: null,
  insightLoading: false,
  insightError: null,
  insightBullets: null,
  hoveredPrecedentId: null,

  initialiseSiteContext: (siteId, siteGeometry) =>
    set({
      siteContext: {
        siteId,
        siteGeometry,
        planningPrecedentFeatures: { type: 'FeatureCollection', features: [] },
        planningContextStats: null,
        statutoryConstraints: emptyConstraints(),
        nearbyContextFeatures: {
          buildings: { type: 'FeatureCollection', features: [] },
          landuse: { type: 'FeatureCollection', features: [] },
          queryRadiusM: 250,
        },
      },
      // Set all loading states immediately so skeletons appear on first render
      loadingStates: { precedent: true, stats: true, constraints: true, contextFeatures: false },
      error: null,
      // Always reset AI insights on every new site selection so the panel
      // re-generates for the new site's evidence rather than showing stale results.
      insight: null,
      insightLoading: false,
      insightError: null,
      insightBullets: null,
      hoveredPrecedentId: null,
    }),

  updateSiteContext: (partial) =>
    set((state) => {
      if (!state.siteContext) return state
      return {
        siteContext: { ...state.siteContext, ...partial },
      }
    }),

  clearSiteContext: () =>
    set({
      siteContext: null,
      loadingStates: DEFAULT_LOADING,
      error: null,
      insight: null,
      insightLoading: false,
      insightError: null,
      insightBullets: null,
      hoveredPrecedentId: null,
    }),

  setLoading: (source, loading) =>
    set((state) => ({
      loadingStates: { ...state.loadingStates, [source]: loading },
    })),

  setError: (error) => set({ error }),

  setInsight: (insight) => set({ insight }),
  setInsightLoading: (loading) => set({ insightLoading: loading }),
  setInsightError: (error) => set({ insightError: error }),
  setInsightBullets: (bullets) => set({ insightBullets: bullets }),
  clearInsight: () => set({ insight: null, insightLoading: false, insightError: null, insightBullets: null }),

  setHoveredPrecedentId: (id) => set({ hoveredPrecedentId: id }),
}))
